require('axios').interceptors.response.use(
    response => response,
    axError => {
        const { url, method } = axError.config ?? {};
        const { code, response } = axError;
        const { status, data } = response ?? {};
        const reason = data?.error /* RFC 6749 */ ?? axError.message;
        const message = (url && method ? `${method.toUpperCase()} ${url} ` : '') +
            'failed' +
            (status || code ? ':' : '') +
            (status ? ` ${status}` : '') +
            (code ? ` ${code}` : '') +
            `. ${reason}.` +
            (data ? ` Details: '${data.error_description /* RFC 6749 */ || require('util').inspect(data)}'.` : '');

        const error = new Error(message);
        if (require('../').debug('req')) {
            error.cause = axError;
        }
        return Promise.reject(error);
    }
);
